name: Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    release:
      types: [published]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: |
          python -m pip install "cibuildwheel==2.3.1"

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.9.0
        env:
          CIBW_SKIP: "cp36* pp* *i686 *musllinux*"
          CIBW_BEFORE_BUILD: "bash {package}/.github/workflows/before_build.sh ${{ matrix.os }}"
          CIBW_BEFORE_TEST: "cp -r {project}/tests .."
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: "SDL_AUDIODRIVER=dummy pytest {project}/../tests"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          name: wheels_${{ matrix.os }}

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
          name: mixstream-sdist.tar.gz
