name: Build

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    release:
      types: [published]

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
          name: mixstream-sdist.tar.gz
