name: Tests

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install os dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -yq install \
            libportmidi-dev \
            libsdl-mixer1.2-dev \
            libsoundtouch-dev \
            libvorbis-dev

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython scikit-build
          python -m pip install pytest

      - name: Test the lib
        run: |
          python setup.py build_ext --inplace --force
          python setup.py check
          python setup.py test
        env:
          SDL_AUDIODRIVER: dummy  # handle alsa issues
